# Generated by Django 4.0.6 on 2022-07-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
